name: Deploy Demo

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  release:
    name: Build, Deploy demo application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install deps & Deploy to Github Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npx nx deploy ngx-cookieconsent-demo
